title: Joseph Beattie

# Minima settings
theme: minima
header_pages:
  - index.md
  - about-me.md
  - resume.md
  - contact.md
author:
no_footer_title: true
no_footer_author: true
copyright: Copyright (c) 2022 Joseph Beattie

# Tipue Search settings
tipue_search:
  include:
    pages: true
